version: 0.0
os: linux
files:
  - source: app.py
    destination: /home/ubuntu/build/target/

permissions:
  - object: /home/ubuntu/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu